-- +goose Up
CREATE TABLE IF NOT EXISTS stops(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    lat DECIMAL(9,6) NOT NULL,
    lng DECIMAL(9,6) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- +goose Down
DROP TABLE IF EXISTS stops;
